package com.myspace.spreadsheet_decisiontable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Keyword implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String value;

	private boolean result;

	public Keyword() {
	}

	public java.lang.String getValue() {
		return value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public boolean isResult() {
		return result;
	}

	public void setResult(boolean result) {
		this.result = result;
	}

	public Keyword(String value, boolean result) {
		this.value = value;
		this.result = result;
	}

}
